const ROLES_LIST = {
  SUPERADMIN: "_SUPERADMIN_",
  ADMIN: "_ADMIN_",
  EMPLOYEE: "_EMPLOYEE_",
  CONTRACTOR: "_CONTRACTOR_",
  CUSTOMER: "_CUSTOMER_",
  JO_CUSTOMER: "customer"
};

module.exports = ROLES_LIST;